version: '3.3'

services:

  server:
    container_name: server 
    build:
        context: ./server
        dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testDb
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_DATASOURCE_USERNAME: 'vio'
      SPRING_DATASOURCE_PASSWORD: '@mySQL123@'
      SERVER.SSL.KEY-STORE-TYPE: 'PKCS12'
      SERVER.SSL.KEY-STORE: valuableAuto.keystore
      SERVER.SSL.KEY-STORE-PASSWORD: '@valuableAuto@'
      SERVER.SSL.KEY-ALIAS: 'valuableAuto'
    links:
      - mysql     
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    ports:
      - 8081:8081

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server  
    volumes:
      - '.:/client'
      - '/client/node_modules'
    ports:
      - '8080:8080'   
      
  mysql:    
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'testDb'
      MYSQL_USER: 'vio'
      MYSQL_PASSWORD: '@mySQL123@'
      MYSQL_ROOT_PASSWORD: '@mySQL123@'    
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 3s
      timeout: 8s
      retries: 20
      start_period: 5s   
